sudo: false
language: python
python: '3.4'
before_install:
- openssl aes-256-cbc -K $encrypted_f4af44f35426_key -iv $encrypted_f4af44f35426_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
install:
- git clone --depth=1 https://github.com/openmicroanalysis/calczaf-github-sync.git
  $TRAVIS_BUILD_DIR/../calczaf-github-sync
- cd $TRAVIS_BUILD_DIR/../calczaf-github-sync
- python setup.py install
- chmod 600 .travis/deploy_key
- eval `ssh-agent -s`
- ssh-add .travis/deploy_key
- git config --global push.default simple
- git config --global user.email "travis@openmicroanalysis.org"
- git config --global user.name "Travis"
script:
- cd $TRAVIS_BUILD_DIR
- calczaf_github_sync -v -w .
notifications:
  email: false
