sudo: false
language: python
python: '3.4'
install:
  - git clone --depth=1 https://github.com/openmicroanalysis/calczaf-github-sync.git $TRAVIS_BUILD_DIR/../calczaf-github-sync
  - cd $TRAVIS_BUILD_DIR/../calczaf-github-sync
  - python setup.py install
script:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - ls
  - git config --global user.email "travis@openmicroanalysis.org"
  - git config --global user.name "Travis"
  - calczaf_github_sync -v -w . --no-push
notifications:
  - email: false
after_success:
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
